apps/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path('entradas/', views.EntryListView.as_view(), name='entradas-lista'),  
    path('entradas/<slug>', views.EntryDetailView.as_view(), name='entradas-detail'),  
]

apps/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path('perfil/', views.UserPageListView.as_view(), name='perfil'), 
    path('agregar-favorito/<pk>/', views.AddFavoritoView.as_view(), name='add-fav'), 
    path('eliminar-favorito/<pk>/', views.FavoritesDeleteView.as_view(), name='delete-fav'), 
]

apps/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),  
    path('contact', views.ContactCreateView.as_view(), name='add-contacto'),  
]

apps/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/', views.UpdatePasswordView.as_view(),name='user-update'),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# SEO
from django.contrib.sitemaps.views import sitemap
from apps.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.home.urls')),
    re_path('', include('apps.entrada.urls')),
    re_path('', include('apps.favoritos.urls')),

    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, 
         name='jango.contrib.sitemaps.views.sitemap'),
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" method="POST" action="{% url 'home_app:add-contacto' %}">
          {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombres
                    <input type="text" placeholder="nombres..." name="full_name" id="id_full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="email" placeholder="Correo ..." name="email" id="id_email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje" name="message" id="id_message"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Enviar</button>
                </div>
            </div>
        </form>
        <!-- Seccion Otras fromas de contactor -->
        <div class="cell small-12, large-7" style="margin-top: 2em;">
          <h3>Otras formas de contacto:</h3>
            <label >Correo Electrónico:
              <span class="label warning">{{ correo }}</span>
            </label>
            <label >Teléfono:
              <span class="label warning">{{ phone }}</span>
            </label>    
        </div>   
        <!-- Fin Otras formas de contacto -->
    </div>
</div>

templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="{% url 'home_app:index' %}" style="font-size: 20px; color: #0277bd;">
                Jonathan Blog
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="{% url 'home_app:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'entrada_app:entradas-lista' %}">Blog</a>
                </li>
                <li>
                    {% if not user.is_anonymous %}
                        <a class="success button" href="{% url 'favoritos_app:perfil' %}">Perfil</a>
                    {% else %}
                        <a class="button" href="{% url 'users_app:user-login' %}">Acceder</a>
                    {% endif %}        
                </li>
                
            </ul>
        </div>
    </div>
</header>