apps/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path('entradas/', views.EntryListView.as_view(), name='entradas-lista'),  
    path('entradas/<slug>', views.EntryDetailView.as_view(), name='entradas-detail'),  
]

apps/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path('perfil/', views.UserPageListView.as_view(), name='perfil'), 
    path('agregar-favorito/<pk>/', views.AddFavoritoView.as_view(), name='add-fav'), 
    path('eliminar-favorito/<pk>/', views.FavoritesDeleteView.as_view(), name='delete-fav'), 
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# SEO
from django.contrib.sitemaps.views import sitemap
from apps.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.home.urls')),
    re_path('', include('apps.entrada.urls')),
    re_path('', include('apps.favoritos.urls')),

    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, 
         name='jango.contrib.sitemaps.views.sitemap'),
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

apps/entrada/models.py
from datetime import datetime, timedelta

from django.db import models
from django.urls import reverse_lazy
from django.conf import settings
from django.template.defaultfilters import slugify

from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

# Managers
from .managers import EntryManager


class Category(TimeStampedModel):
    """Categorias de una entraga
    """
    short_name = models.CharField('Nombre corto', max_length=15, unique=True)
    name = models.CharField('Nombre', max_length=30)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self) -> str:
        return self.name
    

class Tag(TimeStampedModel):
    """Etiquetas de un articulo"""

    name = models.CharField('Nombre', max_length=30)

    
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self) -> str:
        return self.name
    

class Entry(TimeStampedModel):
    """Modelo para las entradas o articulos"""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    title = models.CharField('Titulo', max_length=200)
    resume = models.TextField('Resume')
    content = RichTextUploadingField('contenido')
    public = models.BooleanField(default=False)
    image = models.ImageField('Imagen', upload_to='Entry')
    portada = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    slug = models.SlugField(editable=False, max_length=300)

    objects = EntryManager()

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse_lazy(
                'entrada_app:entradas-detail',
                kwargs={
                    'slug': self.slug
                }
            )
    
    def save(self, *args, **kwargs):
        # Calcular el total de segundos de la horaactual
        now = datetime.now()
        total_time = timedelta(
            hours = now.hour,
            minutes = now.minute,
            seconds = now.second
        )
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.title, str(seconds))

        self.slug = slugify(slug_unique)

        super(Entry, self).save(*args, **kwargs)

apps/entrada/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Entry, Category

class EntryListView(ListView):
    template_name = "entrada/lista.html"
    context_object_name = 'entradas'
    paginate_by = 10

    
    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categorias'] = Category.objects.all()
        return context
    

    def get_queryset(self):
        kw = self.request.GET.get('kword', '')
        categoria = self.request.GET.get('categoria', '')
        # Consulta de entradas
        result = Entry.objects.buscar_entrada(kw, categoria)

        return result



class EntryDetailView(DetailView):
    model = Entry
    template_name = "entrada/detail.html"
    context_object_name = 'entrada'

templates/entrada/base_entrada.html
{% extends "base.html" %}

{% load  static %}

<title>{% block title %}{% endblock title %}</title>

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/entrada/detail.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}

{% load  static %}

{% block title %}
    {{ entrada.title }}
{% endblock title %}

{% block description %}
    <meta name="description" content="{{ entrada.resume }}">
{% endblock description %}

{% block tags %}
      <meta name="keywords" content="{% for tag in entrada.tag.all %} {{ tag.name }}, {% endfor %}">
{% endblock tags %}
    

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <h3 class="cell">{{ entrada.title }}</h3>

        <!-- bloque de contenido del articulo -->
        <div class="cell large-8">
            <div class="cell callout primary">
                <h5>Resumen:</h5>
                <p>{{ entrada.resume }}</p>
            </div>
            <div>
                <p>{{ entrada.content | safe }}</p>
            </div>
        </div>
        <!-- FIN bloque contenido del articulo -->

        <!-- bloque llamada a la accion -->
        <div class="cell large-4">
            <div class="card" style="width: 100%;">
                <img src="{{ entrada.image.url }}">
                <div class="card-section" style="width: 100%;">
                  <form class="blog-action" method="POST" action="{% url 'favoritos_app:add-fav' entrada.slug %}">
                    {% csrf_token %}
                    <button type="submit" class="button alert">Agregar a Favoritos</button>
                  </form>
                </div>
            </div>
        </div>
        <!-- FIN bloque llamada a la accion -->

    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

templates/entrada/lista.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}

{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- primer bloque pantalla blog -->
        <div class="cell small-12 large-8">

            <!-- bloque de buscador -->
            <form class="input-group" method="GET">
                {% csrf_token %}
                <input class="input-group-field" type="text" id="kword" name="kword" placeholder="Buscar ...">
                <div class="input-group-button">
                  <input type="submit" class="button" value="Buscar">
                </div>
            </form>
            <!-- FIN bloque de formulario -->

            <!-- inicio bloque de resultados de busqueda -->
            <div class="grid-x grid-margin-x">
                {% for entrada in entradas %}
                    <div class="cell small-6 large-4">
                        <div class="card" style="width: 100%;">
                            <img src="{{ entrada.image.url }}" style="width: 300;">
                            <div class="card-section">
                                <h4><a href="{% url 'entrada_app:entradas-detail' entrada.slug %}">{{ entrada.title | truncatechars:40 }}</a></h4>
                            <p>{{ entrada.resume | truncatechars:100 }}</p>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h3>Sin resultados</h3>
                {% endfor %}
            <!-- FIN bloque de resultados de busqueda -->
            </div>
        </div>
        <!-- FIN primer bloque pantalla blog -->


        <!-- inicio del segundo bloque - categorias -->
        <div class="cell small-12 large-4" style="height: 500px;">
            <h4>Categorias</h4>
            <ul class="vertical menu">
                {% for categoria in categorias %}
                    <li><a href="?categoria={{ categoria.short_name }}">{{ categoria.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <!-- FIN inicio del segundo bloque - categorias -->
    </div>

    <!-- inicio de bloque de paginacion -->
    <div class="cell">
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="pagination-previous disabled">
                    <a href="?page={{page_obj.previous_page_number}}">Previous</a>
                </li>
                {% endif %}

                {% for pagina in paginator.page_range %}
                
                {% if pagina == page_obj.number  %} 
                    <li class="current"><span class="show-for-sr"></span>{{ pagina }}</li>
                {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %} 
    </div>
    <!-- FIN bloque de paginacion -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}